#ifndef IMAGE_TRANSFORMER_STATUS_ENUMS_H
#define IMAGE_TRANSFORMER_STATUS_ENUMS_H

enum open_stat {
    OPEN_OK,
    OPEN_ERR,
};

enum close_stat {
    CLOSE_OK,
    CLOSE_ERR_NO_STREAM,
    CLOSE_FAILED,
};

enum read_stat {
    READ_OK,
    READ_ERR_OPEN_FAILED,
    READ_ERR_CLOSE_FAILED,
    READ_ERR_HEADER_INVALID,
    READ_ERR_PIXELS_INVALID_RESOLUTION,
    READ_ERR_PIXELS_INVALID_VALUES,
};

enum write_stat {
    WRITE_OK,
    WRITE_ERR_OPEN,
    WRITE_ERR_CLOSE,
    WRITE_ERR_INVALID_FILE,
    WRITE_ERR_INVALID_HEADER,
    WRITE_ERR_PIXELS,
};
#endif
